allowBuilds:
  '@prisma/engines': true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@ai-sdk/anthropic@3.0.91'
  - '@ai-sdk/provider-utils@4.0.34'
  - '@ai-sdk/provider@3.0.13'
onlyBuiltDependencies:
  - '@prisma/engines'
  - better-sqlite3
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
overrides:
  'ali-oss>urllib': 4.9.0
