allowBuilds:
  '@prisma/engines': true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  prisma: true
  sharp: true
onlyBuiltDependencies:
  - '@prisma/engines'
  - better-sqlite3
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
overrides:
  'ali-oss>urllib': 4.9.0
