/**
 * 统一错误码与 HTTP 状态映射（PDC §13）。
 * Phase 1 覆盖认证/用户相关；License 相关错误码 Phase 2 补齐。
 */
export const ErrorCode = {
  // 通用
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  RATE_LIMITED: "RATE_LIMITED",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  // 认证 / 用户
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  EMAIL_CODE_INVALID: "EMAIL_CODE_INVALID",
  EMAIL_CODE_EXPIRED: "EMAIL_CODE_EXPIRED",
  EMAIL_CODE_TOO_MANY_ATTEMPTS: "EMAIL_CODE_TOO_MANY_ATTEMPTS",
  PASSWORD_INVALID: "PASSWORD_INVALID",
  PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  // License（Phase 3 客户端 API 主要使用，Phase 2 管理端复用部分）
  LICENSE_INVALID: "LICENSE_INVALID",
  LICENSE_DISABLED: "LICENSE_DISABLED",
  LICENSE_REVOKED: "LICENSE_REVOKED",
  LICENSE_EXPIRED: "LICENSE_EXPIRED",
  DEVICE_LIMIT_EXCEEDED: "DEVICE_LIMIT_EXCEEDED",
  DEVICE_MISMATCH: "DEVICE_MISMATCH",
  ACTIVATION_REVOKED: "ACTIVATION_REVOKED",
  SIGNATURE_INVALID: "SIGNATURE_INVALID",
  REPLAY_DETECTED: "REPLAY_DETECTED",
  // 支付
  PAYMENT_PROVIDER_ERROR: "PAYMENT_PROVIDER_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const HTTP_STATUS: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  RATE_LIMITED: 429,
  PAYLOAD_TOO_LARGE: 413,
  UNSUPPORTED_MEDIA_TYPE: 415,
  INTERNAL_ERROR: 500,
  INVALID_CREDENTIALS: 401,
  ACCOUNT_DISABLED: 403,
  EMAIL_ALREADY_REGISTERED: 409,
  EMAIL_CODE_INVALID: 400,
  EMAIL_CODE_EXPIRED: 400,
  EMAIL_CODE_TOO_MANY_ATTEMPTS: 429,
  PASSWORD_INVALID: 400,
  PASSWORD_MISMATCH: 400,
  METHOD_NOT_ALLOWED: 405,
  LICENSE_INVALID: 400,
  LICENSE_DISABLED: 403,
  LICENSE_REVOKED: 403,
  LICENSE_EXPIRED: 403,
  DEVICE_LIMIT_EXCEEDED: 409,
  DEVICE_MISMATCH: 403,
  ACTIVATION_REVOKED: 403,
  SIGNATURE_INVALID: 401,
  REPLAY_DETECTED: 401,
  PAYMENT_PROVIDER_ERROR: 502,
};

/** 业务错误，携带稳定错误码与 HTTP 状态。 */
export class AppError extends Error {
  readonly code: ErrorCode;
  readonly status: number;
  readonly details?: unknown;
  constructor(code: ErrorCode, message?: string, details?: unknown) {
    super(message ?? code);
    this.name = "AppError";
    this.code = code;
    this.status = HTTP_STATUS[code];
    this.details = details;
  }
}
