"use client";
import { useEffect, useState } from "react";
import { Loader2, Pencil, Plus, Star, TestTube2, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
type Account={id:string;name:string;appId:string;tagsJson:string;isDefault:boolean;status:string;lastError?:string|null};
export function WechatAccountsManager(){
 const [items,setItems]=useState<Account[]>([]); const [open,setOpen]=useState(false); const [editingId,setEditingId]=useState<string|null>(null); const [testingId,setTestingId]=useState<string|null>(null); const [testResult,setTestResult]=useState<{id:string;ok:boolean;message:string;guidance?:string}|null>(null); const [form,setForm]=useState({name:"",appId:"",secret:"",tags:""}); const [error,setError]=useState("");
 const load=async()=>{ try { const r=await fetch("/api/wechat/accounts"); const d=await r.json().catch(()=>null); if(!r.ok) throw new Error(d?.error||"账号列表加载失败"); setItems(d?.accounts??[]); } catch(e) { setError(e instanceof Error?e.message:"账号列表加载失败"); } }; useEffect(()=>{void load()},[]);
 async function save(){setError("");const body={...form,tags:form.tags.split(",").map(x=>x.trim()).filter(Boolean)}; const r=await fetch(editingId?`/api/wechat/accounts/${editingId}`:"/api/wechat/accounts",{method:editingId?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(editingId?{...body,secret:form.secret||undefined}:body)});const data=await r.json().catch(()=>({}));if(!r.ok){setError(data.error||"保存失败");return}setOpen(false);setEditingId(null);setForm({name:"",appId:"",secret:"",tags:""});load()}
 function openCreate(){setEditingId(null);setForm({name:"",appId:"",secret:"",tags:""});setError("");setOpen(true)}
 function openEdit(account:Account){setEditingId(account.id);setForm({name:account.name,appId:account.appId,secret:"",tags:JSON.parse(account.tagsJson||"[]").join(", ")});setError("");setOpen(true)}
 async function patch(id:string,data:object){await fetch(`/api/wechat/accounts/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(data)});load()}
 async function testConnection(id:string){setTestingId(id);setTestResult(null);try{const r=await fetch(`/api/wechat/accounts/${id}`,{method:"POST"});const data=await r.json().catch(()=>({}));setTestResult({id,ok:!!r.ok,message:data.message||data.error||"测试失败",guidance:data.guidance});await load()}catch{setTestResult({id,ok:false,message:"网络错误，无法完成连通性测试。",guidance:"请检查本机或服务器网络后重试。"})}finally{setTestingId(null)}}
 return <div className="space-y-4"><div className="rounded-lg border bg-muted/30 p-4 text-sm text-muted-foreground">每个公众号独立保存凭证、素材同步记录和草稿箱 ID。默认账号只用于预选，发布时仍可切换。</div>
  <div className="space-y-2">{items.map(a=><div key={a.id} className="rounded-lg border p-3"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-emerald-100 font-semibold text-emerald-700">{a.name.slice(0,1)}</div><div className="min-w-0 flex-1"><div className="flex gap-2 text-sm font-medium">{a.name}{a.isDefault&&<span className="text-xs text-amber-600">默认</span>}</div><div className="text-xs text-muted-foreground">AppID：{a.appId} · {a.status==="active"?"可用":"已停用"}</div></div><Button variant="outline" size="sm" onClick={()=>testConnection(a.id)} disabled={testingId===a.id} title="测试连通性">{testingId===a.id?<Loader2 className="h-4 w-4 animate-spin"/>:<TestTube2 className="h-4 w-4"/>}{testingId===a.id?"测试中":"测试"}</Button><Button variant="ghost" size="sm" onClick={()=>openEdit(a)} title="编辑公众号认证" aria-label="编辑公众号认证"><Pencil className="h-4 w-4"/></Button><Button variant="ghost" size="sm" className={a.isDefault?"opacity-100 hover:bg-transparent":""} onClick={()=>patch(a.id,{isDefault:true})} title={a.isDefault?"当前默认公众号":"设为默认"} aria-label={a.isDefault?"当前默认公众号":"设为默认"} disabled={a.isDefault}><Star className={a.isDefault?"h-4 w-4 fill-amber-400 text-amber-500":"h-4 w-4"}/></Button><Button variant="ghost" size="sm" onClick={()=>{if(confirm(`移除 ${a.name}？其发布记录会保留。`))fetch(`/api/wechat/accounts/${a.id}`,{method:"DELETE"}).then(load)}}><Trash2 className="h-4 w-4 text-destructive"/></Button></div>{testResult?.id===a.id&&<div className={testResult.ok?"mt-3 rounded-md border border-emerald-200 bg-emerald-50 p-2 text-xs text-emerald-700":"mt-3 rounded-md border border-amber-200 bg-amber-50 p-2 text-xs text-amber-800"}><div className="font-medium">{testResult.ok?"✓ ":"无法连接："}{testResult.message}</div>{testResult.guidance&&<div className="mt-1 leading-relaxed">处理建议：{testResult.guidance}</div>}</div>}</div>)}{!items.length&&<div className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">尚未添加公众号</div>}</div>
  {open?<div className="space-y-3 rounded-lg border p-4"><div className="text-sm font-medium">{editingId?"编辑公众号认证":"添加公众号"}</div><div className="grid gap-3 sm:grid-cols-2"><div><Label>内部名称</Label><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="品牌 A 官方号"/></div><div><Label>AppID</Label><Input value={form.appId} onChange={e=>setForm({...form,appId:e.target.value})}/></div></div><div><Label>AppSecret</Label><Input type="password" value={form.secret} onChange={e=>setForm({...form,secret:e.target.value})} placeholder={editingId?"留空则保持原密钥":""}/></div><div><Label>标签（逗号分隔，可选）</Label><Input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="品牌A, 国内"/></div>{error&&<p className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setOpen(false)}>取消</Button><Button onClick={save}>保存账号</Button></div></div>:<Button onClick={openCreate}><Plus className="h-4 w-4"/> 添加公众号</Button>}
 </div>
}
